'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {Store,OWNER}=require('../src/store');const {addStat,emptyStats,canDiscard}=require('../src/util');const {Manager}=require('../src/manager');const {Worker}=require('../src/worker');const EventEmitter=require('node:events');const {Vec3}=require('vec3');
function store(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'asira-test-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));return new Store(dir);}
test('MC command authorization requires exact MCID and matching XUID from player_list; formatted messages rejected',t=>{const s=store(t);s.adminAdd('Asira Test','2535420012345678');const players=new Map([['asira test',{xuid:'2535420012345678'}]]);const p={type:'chat',source_name:'Asira Test',xuid:'2535420012345678'};assert(s.authorized(p,players));for(const bad of [{...p,type:'system'},{...p,xuid:''},{...p,xuid:'1111111111111111'},{...p,source_name:'someone'}])assert(!s.authorized(bad,players));assert.equal(OWNER,'1343843235252146219');});
test('stats persist and ordinary scaffolding does not increment mining totals',t=>{const s=store(t);const b=s.bot(1);addStat(b.stats,'obsidian');addStat(b.stats,'stone');s.save();const reopened=new Store(s.dir);assert.deepEqual(reopened.bot(1).stats,{total:2,obsidian:1,other:1,byBlock:{obsidian:1,stone:1}});assert(canDiscard('obsidian','slime'));assert(!canDiscard('slime','slime'));assert(!canDiscard('enchanted_golden_apple','slime'));assert(!canDiscard('diamond_pickaxe','slime'));assert(!canDiscard('red_shulker_box','slime'));});
test('all targets and coordinates normalized; game cannot connect or clear recovery',async t=>{const s=store(t);const m=new Manager(s);t.after(()=>{clearTimeout(m.chatTimer);});await m.execute('all','area 20 30 -20 -30');await m.execute('1','floor 64');assert.deepEqual(s.bot(1).area,{x1:-20,z1:-30,x2:20,z2:30});assert.equal(s.bot(1).floor,64);await assert.rejects(m.execute('1','connect','game'));await assert.rejects(m.execute('1','clear-recovery confirm','game'));await assert.rejects(m.execute('2','stop'));});
test('receive waits for positive quantity change and block delivery, stop cancels restart',async t=>{const s=store(t);const manager={store:s,workers:new Map(),notice:()=>{}};const bot=new EventEmitter();Object.assign(bot,{halt:()=>{},connected:true,registry:{blocksByName:{slime:{}}},name:()=> 'slime',health:20,tool:()=>({}),find:()=>({})});const w=new Worker(manager,1,bot);t.after(()=>clearInterval(w.timer));s.bot(1).area={x1:0,z1:0,x2:1,z2:1};s.bot(1).floor=64;w.receive();await w.tick();assert(w.receiving);bot.emit('inventory',null,{network_id:123,count:1});await w.tick();assert(w.receiving);w.lastReceive=Date.now()-3100;await w.tick();assert(w.running);w.receive();bot.emit('inventory',null,{network_id:123,count:1});w.stop();w.lastReceive=Date.now()-3100;await w.tick();assert(!w.running);});
test('floor protection includes the floor; own scaffold or other bots footing skipped',t=>{const s=store(t);const manager={store:s,workers:new Map(),notice:()=>{}};const bot=new EventEmitter();Object.assign(bot,{halt:()=>{},connected:false,dimensionId:0,entity:{position:new Vec3(.5,65,.5)}});const w=new Worker(manager,1,bot);manager.workers.set(1,w);t.after(()=>clearInterval(w.timer));w.state.area={x1:-2,z1:-2,x2:2,z2:2};w.state.floor=64;assert(!w.inArea(new Vec3(0,64,0)));assert(w.inArea(new Vec3(0,65,0)));assert(w.underPlayer(new Vec3(0,64,0)));});
test('inventory discards exactly a full stack spread across slots, preserves scaffold',async t=>{const s=store(t);const manager={store:s,workers:new Map(),notice:()=>{}};const drops=[];const bot=new EventEmitter();Object.assign(bot,{halt:()=>{},connected:false,registry:{itemsByName:{obsidian:{stackSize:64},slime:{stackSize:64}}},list:()=>[{name:'obsidian',slot:0,count:32},{name:'obsidian',slot:1,count:32},{name:'slime',slot:2,count:64}],drop:async(slot,count)=>drops.push([slot,count])});const w=new Worker(manager,1,bot);t.after(()=>clearInterval(w.timer));w.state.minedItems=['obsidian','slime'];await w.discard(new AbortController().signal);assert.deepEqual(drops,[[0,32],[1,32]]);});
